FROM alpine

RUN apk add --no-cache task ruby python \
 && apk add --no-cache --virtual .build-dependencies \
            ruby-dev \
            make \
            g++ \
            git

COPY docker/.taskrc /root/.taskrc

COPY . /opt/app

WORKDIR /opt/app

RUN GEM=$(gem build taskwarrior-web.gemspec | awk '/File: .*/{ print $2 }') \
 && gem install ${GEM} --no-document

RUN apk del --no-cache .build-dependencies

EXPOSE 5678

CMD task-web -F -L